using System;
using System.Collections.Generic;

namespace CoreBackend.Model
{
    /*
     * This is generated by the following code:
     * dotnet ef dbcontext scaffold "Server=myaibig1.mysql.rds.aliyuncs.com;Database=noisycity;User ID=ncbackend;Password=Jft23333;" Pomelo.EntityFrameworkCore.MySql -o Model
     * Note the result is not completely the same as what it is in MySQL, two fields type of POINT are missing
     * EF Core 2 doesn't not support Spatial data types for now!
     * A workaround can be https://stackoverflow.com/questions/44873740/entity-framework-core-type-udt-is-not-supported-on-this-platform-spatial-data
     */
    public partial class User
    {
        public long Uid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public sbyte EmailConfirmed { get; set; }
        public string Phone { get; set; }
        public sbyte PhoneConfirmed { get; set; }
        public string Bio { get; set; }
        public string AvatarPath { get; set; }
        public DateTimeOffset CreateTime { get; set; }
        public DateTimeOffset LastTimeUsernameChanged { get; set; }
        public sbyte LanguageFirst { get; set; }
        public sbyte LanguageSecond { get; set; }
    }
}
